name: speedmart_admin_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number.
# In Android, build-name is used as versionName while build-number used as versionCode.
# In iOS, build-name is used as CFBundleShortVersionString while build-number is
# used as CFBundleVersion.
# Read more about Android versioning at
# following page: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and build-number as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.4
  dio: ^5.6.0
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.2.2
  google_fonts: ^8.1.0
  uuid: ^4.5.3
  flutter_svg: ^2.0.10
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  image_cropper: ^9.0.0
  geolocator: ^12.0.0
  flutter_map: ^7.0.1
  latlong2: ^0.9.0
  url_launcher: ^6.3.2
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/admin_login_bg.png
    - assets/images/
